# yaml-language-server: $schema=https://render.com/schema/render.yaml.json
services:
  - type: web
    name: no-home-backend
    runtime: docker
    plan: free
    region: singapore
    dockerContext: ./Backend
    dockerfilePath: ./Backend/Dockerfile
    healthCheckPath: /api/health
    autoDeployTrigger: "off"
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JWT_COOKIE_SECURE
        value: "true"
      - key: JAVA_TOOL_OPTIONS
        value: -XX:InitialRAMPercentage=25.0 -XX:MaxRAMPercentage=75.0
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
