CREATE TABLE regions (
    region_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lawd_cd VARCHAR(5) NOT NULL,
    legal_dong_code VARCHAR(10),
    sido VARCHAR(50) NOT NULL,
    sigungu VARCHAR(50) NOT NULL,
    umd_nm VARCHAR(50) NOT NULL,
    lat NUMERIC(10, 7),
    lng NUMERIC(10, 7),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_regions_lawd_umd UNIQUE (lawd_cd, umd_nm)
);

CREATE INDEX idx_regions_lawd_cd ON regions (lawd_cd);

CREATE TABLE houses (
    house_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_id BIGINT NOT NULL,
    sgg_cd VARCHAR(5) NOT NULL,
    umd_nm VARCHAR(50) NOT NULL,
    jibun VARCHAR(30) NOT NULL,
    apt_nm VARCHAR(100) NOT NULL,
    build_year INTEGER,
    lat NUMERIC(10, 7),
    lng NUMERIC(10, 7),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_houses_source_identity UNIQUE NULLS NOT DISTINCT (sgg_cd, umd_nm, jibun, apt_nm, build_year),
    CONSTRAINT fk_houses_region FOREIGN KEY (region_id) REFERENCES regions (region_id)
);

CREATE INDEX idx_houses_apt_nm ON houses (apt_nm);
CREATE INDEX idx_houses_region_id ON houses (region_id);

CREATE TABLE house_deals (
    deal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    house_id BIGINT NOT NULL,
    source_api VARCHAR(64) NOT NULL,
    lawd_cd VARCHAR(5) NOT NULL,
    deal_ymd CHAR(6) NOT NULL,
    house_type VARCHAR(30) NOT NULL DEFAULT 'apartment',
    deal_type VARCHAR(30) NOT NULL DEFAULT 'sale',
    deal_year INTEGER NOT NULL,
    deal_month INTEGER NOT NULL,
    deal_day INTEGER NOT NULL,
    deal_date DATE NOT NULL,
    deal_amount VARCHAR(32) NOT NULL,
    deal_amount_manwon INTEGER,
    rent_type VARCHAR(30),
    deposit VARCHAR(32),
    deposit_manwon INTEGER,
    monthly_rent VARCHAR(32),
    monthly_rent_manwon INTEGER,
    exclu_use_ar NUMERIC(10, 3),
    floor INTEGER,
    apt_dong VARCHAR(50),
    buyer_gbn VARCHAR(50),
    sler_gbn VARCHAR(50),
    dealing_gbn VARCHAR(50),
    estate_agent_sgg_nm VARCHAR(100),
    cdeal_type VARCHAR(30),
    cdeal_day VARCHAR(30),
    rgst_date VARCHAR(30),
    land_leasehold_gbn VARCHAR(30),
    contract_term VARCHAR(30),
    contract_type VARCHAR(30),
    use_rr_right VARCHAR(30),
    pre_deposit VARCHAR(32),
    pre_deposit_manwon INTEGER,
    pre_monthly_rent VARCHAR(32),
    pre_monthly_rent_manwon INTEGER,
    roadnm VARCHAR(100),
    apt_seq VARCHAR(30),
    api_row_hash CHAR(64) NOT NULL,
    raw_response JSONB,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_house_deals_api_row_hash UNIQUE (api_row_hash),
    CONSTRAINT fk_house_deals_house FOREIGN KEY (house_id) REFERENCES houses (house_id)
);

CREATE INDEX idx_house_deals_lawd_ymd ON house_deals (lawd_cd, deal_ymd);
CREATE INDEX idx_house_deals_house_date ON house_deals (house_id, deal_date);
CREATE INDEX idx_house_deals_deal_mode ON house_deals (deal_type, lawd_cd, deal_ymd);

CREATE TABLE public_data_import_batches (
    import_batch_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_api VARCHAR(64) NOT NULL,
    lawd_cd VARCHAR(5) NOT NULL,
    deal_ymd CHAR(6) NOT NULL,
    house_type VARCHAR(30) NOT NULL DEFAULT 'apartment',
    deal_type VARCHAR(30) NOT NULL DEFAULT 'sale',
    status VARCHAR(20) NOT NULL,
    total_count INTEGER NOT NULL DEFAULT 0,
    imported_count INTEGER NOT NULL DEFAULT 0,
    skipped_count INTEGER NOT NULL DEFAULT 0,
    error_message TEXT,
    requested_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP WITHOUT TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_import_batches_request UNIQUE (source_api, lawd_cd, deal_ymd, house_type, deal_type)
);

CREATE INDEX idx_import_batches_lawd_ymd ON public_data_import_batches (lawd_cd, deal_ymd);

CREATE TABLE members (
    member_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    name VARCHAR(100) NOT NULL,
    phone VARCHAR(30),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_members_email UNIQUE (email)
);

CREATE TABLE member_refresh_tokens (
    member_id BIGINT PRIMARY KEY,
    token_hash CHAR(64) NOT NULL,
    expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_member_refresh_tokens_hash UNIQUE (token_hash),
    CONSTRAINT fk_member_refresh_tokens_member FOREIGN KEY (member_id) REFERENCES members (member_id) ON DELETE CASCADE
);

CREATE TABLE notices (
    notice_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notices_member FOREIGN KEY (member_id) REFERENCES members (member_id) ON DELETE CASCADE
);

CREATE INDEX idx_notices_created_at ON notices (created_at);
CREATE INDEX idx_notices_member_id ON notices (member_id);

CREATE TABLE interest_regions (
    interest_region_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    region_id BIGINT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_interest_regions_member_region UNIQUE (member_id, region_id),
    CONSTRAINT fk_interest_regions_member FOREIGN KEY (member_id) REFERENCES members (member_id) ON DELETE CASCADE,
    CONSTRAINT fk_interest_regions_region FOREIGN KEY (region_id) REFERENCES regions (region_id) ON DELETE CASCADE
);

CREATE INDEX idx_interest_regions_member_id ON interest_regions (member_id);
CREATE INDEX idx_interest_regions_region_id ON interest_regions (region_id);
